defaults: &defaults
  host: localhost
  port: 6379
  db: 0
  cache_db: 2

development:
  <<: *defaults

test:
  <<: *defaults 
  db: 1

staging:
  <<: *defaults

production:
  host: ENV["REDIS_HOST"]
  password: ENV["REDIS_PASSWORD"]
  port: ENV["REDIS_PORT"]

