defaults: &defaults
  host: localhost
  port: 6379
  db: 0
  cache_db: 2

development:
  <<: *defaults

test:
  <<: *defaults 
  db: 1

staging:
  <<: *defaults

production:
  host: #{Figaro.env.redis_host}
  port: #{Figaro.env.redis_port}
  password: #{Figaro.env.redis_password}

